# https://www.mkdocs.org/user-guide/configuration/#configuration

# Project information
site_author: MLOps University
site_name: MLOps Coding Course
site_url: https://mlops-university.github.io/mlops-coding-course/
site_description: Learn how to create, develop, and maintain an MLOps code base.

# Repository
repo_name: MLOPS-University/mlops-coding-course
repo_url: https://github.com/MLOPS-University/mlops-coding-course

# Copyright
copyright: Copyright &copy; MLOps University

# Theme
theme:
  name: material
  # favicon: images/favicon.ico
  palette:
    scheme: default
    primary: indigo

  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MLOPS-University/mlops-coding-course

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format