# https://www.mkdocs.org/user-guide/configuration/#configuration

repo_name: MLOPS-Teaching/mlops-coding-course
repo_url: https://github.com/MLOPS-Teaching/mlops-coding-course
site_name: MLOps Coding Course
site_description: Learn how to create and maintain MLOps code base.
# site_url: TODO
theme:
  name: material
