# https://www.mkdocs.org/user-guide/configuration/#configuration

# Project information
site_author: MLOps Courses
site_name: MLOps Coding Course
site_url: https://mlops-courses.github.io/mlops-coding-course/
site_description: Learn how to create, develop, and maintain a state-of-the-art MLOps projects.

# Repository
repo_name: MLOPS-Courses/mlops-coding-course
repo_url: https://github.com/MLOPS-Courses/mlops-coding-course

# Copyright
copyright: Copyright &copy; MLOps Courses

# Configs
use_directory_urls: false
strict: true

# Theme
theme:
  name: material
  # favicon: images/favicon.ico
  palette:
    scheme: default
    primary: indigo

  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MLOPS-Courses/mlops-coding-course

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format