# https://docs.astral.sh/uv/reference/settings/
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

# PROJECT

[project]
name = "mlops-coding-course"
version = "7.0.0"
description = "Learn how to create, develop, and maintain a state-of-the-art MLOps code base."
authors = [{ name = "Médéric HURIER", email = "github@fmind.dev" }]
readme = "README.md"
requires-python = ">=3.14"
license = "CC-BY-4.0"
license-files = ["LICENSE.txt"]
keywords = ["mlops", "python", "course", "best-practices", "machine-learning"]
dependencies = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.7.6",
]

# LINKS

[project.urls]
Homepage = "https://mlops-coding-course.fmind.dev/"
Documentation = "https://mlops-coding-course.fmind.dev/"
Repository = "https://github.com/MLOps-Courses/mlops-coding-course"

# DEPENDENCIES

[dependency-groups]
dev = [
  "pip-audit>=2.10.1",
  "validate-pyproject>=0.25",
]

# TOOLS

[tool.uv]
package = false
